name: IndulgeMagazine
favicon: null
layout_spectrum: 0.7503
typography_spectrum: 0.49759
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5a7a93'
    - '#fffefc'
    - '#354959'
    - '#9aaebb'
    - '#beccd5'
  brandStrength: 0.4381210491992533
  lightness: 0.8562542460858822
  saturation: 0.32264120457693934
  rhythmicContrast: 0.6902864535804838
purpose: []
